spring:
  mvc:
    view:
      #mvc视图解析
      prefix: classpath:/templates/
      suffix: .html
  datasource:
      name: default
      url: jdbc:mysql://192.168.5.74:3306/mydatabase?useUnicode=true&amp;characterEncoding=UTF-8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
       host: 192.168.5.188
       port: 6379
       password: tj720!@
server:
  port: 8888
  servlet:
    path: /demo
  thymeleaf:
    cache: false
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tj720.demo.Modle
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql